In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
l=range(100)
%timeit [i**2 for i in l]# used to calculate the time for each iteration

4.83 µs ± 238 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# creating arrays

In [5]:
a=np.array([1,2,3,4,5])
print(a.ndim)

1


In [6]:
b=np.array([[1,2,3],[4,5,6]])
print(b.ndim)
print(b)

2
[[1 2 3]
 [4 5 6]]


In [7]:
c=np.array([[[1,2],[3,4],[5,6]]])
print(c.ndim)
print(c)

3
[[[1 2]
  [3 4]
  [5 6]]]


In [8]:
c=np.array([[[1,2],[2,3]],[[4,5],[6,7]]])
print(c)

[[[1 2]
  [2 3]]

 [[4 5]
  [6 7]]]


In [9]:
print(c.ndim)

3


In [10]:
print(c.shape)

(2, 2, 2)


In [11]:
print(a.shape)

(5,)


In [12]:
print(b.shape)

(2, 3)


# Functions for creating array

In [13]:
a=np.arange(1,10,2)# give the jump values 
print(a)

[1 3 5 7 9]


In [14]:
a=np.linspace(0,1,5)# using display 5 values
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [15]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
a=np.eye(4,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [20]:
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [21]:
print(np.diag(a))

[1 2 3 4]


# Basic data types

In [22]:
a=np.arange(10)
print(a.dtype)

int32


In [23]:
a = np.arange(10,dtype="float64")
print(a.dtype

SyntaxError: incomplete input (189387362.py, line 2)

In [25]:
a = np.arange(10,dtype="float64")
print(a.dtype)

float64


In [26]:
a=np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


In [27]:
a=np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [28]:
a=np.array([True,False])
print(a.dtype)

bool


In [29]:
a=np.array(["niha","Nihas"])
print(a.dtype) #unicode string type

<U5


# indexing and slicing

In [30]:
a=np.arange(10)
print(a[5])

5


In [31]:
a=np.diag([1,2,3])
print(a[2,2])

3


In [32]:
a[2,1]=5
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


In [33]:
a=np.arange(10)
print(a)    

[0 1 2 3 4 5 6 7 8 9]


In [34]:
print(a[1:8:2])

[1 3 5 7]


In [35]:
a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

# copies and viewing

In [36]:
a=np.arange(10)
b=a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [37]:
print(np.shares_memory(a,b))

True


In [38]:
b[0]=10 #viewing
print(a)
print(b)

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [39]:
a=np.arange(10)
b=a[::2].copy() #force a copy
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [40]:
print(np.shares_memory(a,b))

False


# Random number genarator

In [41]:
a=np.random.randint(0,20,15)
print(a)

[11 19 13 12  6  3 11 15 18 16  0 15  6 14 12]


In [42]:
mask=(a%2==0)

In [43]:
mask_a = a[mask]
print(mask_a)

[12  6 18 16  0  6 14 12]


In [44]:
a[mask]=-1
print(a)

[11 19 13 -1 -1  3 11 15 -1 -1 -1 15 -1 -1 -1]
