# Covariance

In [5]:
import pandas as pd
df=pd.read_csv(r"C:\Users\prashanthi\Downloads\study_marks.csv")
df

Study_Hours  Marks
0          2.9   27.0
1          5.8   61.0
2          4.7   45.0
3          4.0   38.0
4          1.8   19.0
5          1.8    8.0
6          1.3    4.0
7          5.3   50.0
8          4.0   35.0
9          4.5   47.0

In [6]:
df.cov()

Study_Hours       Marks
Study_Hours     2.481000   28.906667
Marks          28.906667  348.711111

# Correlation

In [7]:
df.corr() 

Study_Hours    Marks
Study_Hours      1.00000  0.98277
Marks            0.98277  1.00000

In [8]:
df.var()

Study_Hours      2.481000
Marks          348.711111
dtype: float64

In [12]:
import pandas as pd
df=pd.read_csv(r"C:\Users\prashanthi\Downloads\study_marks.csv")
df

Study_Hours  Marks
0          2.9   27.0
1          5.8   61.0
2          4.7   45.0
3          4.0   38.0
4          1.8   19.0
5          1.8    8.0
6          1.3    4.0
7          5.3   50.0
8          4.0   35.0
9          4.5   47.0

In [13]:
df.var()

Study_Hours      2.481000
Marks          348.711111
dtype: float64

In [14]:
df.corr()

Study_Hours    Marks
Study_Hours      1.00000  0.98277
Marks            0.98277  1.00000

In [15]:
df.cov()

Study_Hours       Marks
Study_Hours     2.481000   28.906667
Marks          28.906667  348.711111

In [16]:
data= {
    "temp": [30,32,34,35,36],   # negative correlation
    "humidity":[40,39,34,28,27]
}
df=pd.DataFrame(data)
df

temp  humidity
0    30        40
1    32        39
2    34        34
3    35        28
4    36        27

In [17]:
df.cov()

temp  humidity
temp       5.8     -13.8
humidity -13.8      36.3

In [18]:
df.var()

temp         5.8
humidity    36.3
dtype: float64

In [19]:
df.corr()

temp  humidity
temp      1.000000 -0.951068
humidity -0.951068  1.000000

# Normalization

#####  Normalization is a technique used to scale the values of features into a small range, usually 0 to 1. It makes all features equal in scale to the model does not get confused by big and small numbers.

## use

### it  have different ranges big numbers dominate small numbers models work better when all values are in same range training becomes faster and more accurate

In [21]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler
import pandas as pd

In [22]:
import pandas as pd 
s=pd.Series([1000,2000,3000,4000,9000])
s

0    1000
1    2000
2    3000
3    4000
4    9000
dtype: int64

In [23]:
s.min()

1000

In [24]:
s.max()

9000

In [25]:
sn=(s-s.min())/(s.max()-s.min())
sn

0    0.000
1    0.125
2    0.250
3    0.375
4    1.000
dtype: float64

In [26]:
sn=MinMaxScaler().fit_transform(s.values.reshape(-1,1))
print(sn)

[[0.   ]
 [0.125]
 [0.25 ]
 [0.375]
 [1.   ]]


In [27]:
data= {
    "temp": [30,32,34,35,36],   
    "humidity":[40,39,34,28,27]
}
df=pd.DataFrame(data)
df
  

temp  humidity
0    30        40
1    32        39
2    34        34
3    35        28
4    36        27

In [28]:
norm_data=MinMaxScaler().fit_transform(df) # to normalize the code
n_df= pd.DataFrame(norm_data,columns=df.columns) # it gives the data in an array
norm_data

array([[0.        , 1.        ],
       [0.33333333, 0.92307692],
       [0.66666667, 0.53846154],
       [0.83333333, 0.07692308],
       [1.        , 0.        ]])

In [29]:
n_df # it displays in a structured format

temp  humidity
0  0.000000  1.000000
1  0.333333  0.923077
2  0.666667  0.538462
3  0.833333  0.076923
4  1.000000  0.000000

# Standardization

#### Standardization or Z score normalization is a scaler technique that transforms data so that : Mean = 0,standard deviation= 1. It shows how far each value is from the mean

## use

#### makes data centered around zero
#### works well when data follows a normal distribution
#### less affected by outliers compared to normalization
#### Helps the model learn more smoothly

# Algorithms

### lOgistic Regression pCA sVM linear regression neural Networks

### range is -->(-infinity,+infinity)


### z= (x=mue)/sigma, mue=mean, sigma= standard deviation

In [30]:
import pandas as pd 
s=pd.Series([1000,2000,3000,4000,9000])
s

0    1000
1    2000
2    3000
3    4000
4    9000
dtype: int64

In [31]:
s.mean()

3800.0

In [32]:
s.std()

3114.4823004794875

In [33]:
z_score=(s-s.mean())/s.std()
print(z_score)

0   -0.899026
1   -0.577945
2   -0.256865
3    0.064216
4    1.669619
dtype: float64


In [34]:
z_score=(s-s.mean())/s.std(ddof=0)
print(z_score)

0   -1.005141
1   -0.646162
2   -0.287183
3    0.071796
4    1.866691
dtype: float64


In [35]:
sn=StandardScaler().fit_transform(s.values.reshape(-1,1)) # standard deviation (n population data)
print(sn)

[[-1.00514142]
 [-0.64616234]
 [-0.28718326]
 [ 0.07179582]
 [ 1.86669121]]


In [36]:
data= {
    "temp": [30,32,34,35,36],   
    "humidity":[40,39,34,28,27]
}
df=pd.DataFrame(data)
df

temp  humidity
0    30        40
1    32        39
2    34        34
3    35        28
4    36        27

In [37]:
norm_data=StandardScaler().fit_transform(df) # to standardize the code
n_df= pd.DataFrame(norm_data,columns=df.columns) # it gives the data in an array
norm_data

array([[-1.57841037,  1.18763139],
       [-0.64993368,  1.00206399],
       [ 0.27854301,  0.07422696],
       [ 0.74278135, -1.03917747],
       [ 1.2070197 , -1.22474487]])

In [38]:
n_df

temp  humidity
0 -1.578410  1.187631
1 -0.649934  1.002064
2  0.278543  0.074227
3  0.742781 -1.039177
4  1.207020 -1.224745